my_toolbox:
  target: dev
  outputs:
    dev:
      type: duckdb
      path: '/opt/airflow/dwh/pokedex.duckdb'
      extensions:
        - parquet
    local:
      type: duckdb
      path: 'C:\Users\ollek\Documents\Projects\local-toolbox\data\pokedex.duckdb'
      extensions:
        - parquet
